export type School = {
  _id: string;
  SchoolID: number;
  SchoolName: string;
  Lat: number;
  Lng: number;
  Type: string;
  ShortName: string;
  CapPK: number;
  CapK: number;
  Cap1: number;
  Cap2: number;
  Cap3: number;
  Cap4: number;
  Cap5: number;
  Cap6: number;
  Cap7: number;
  Cap8: number;
  Capacity: object;
};
