export default {
  submissions: [
    {
      submissionId: "35415841",
      completedAt: "2023-08-01T15:34:37.9825590Z",
      FullName: "Rasan Norwood ",
      EnteringPreK: "No",
      ParentFirstName: "Daijanair ",
      ParentLastName: "Johnson ",
      ParentPhone: "+13138549356",
      ParentEmail: "Johnsondaijanair@yahoo.com",
      FirstName: "Rasan ",
      LastName: "Norwood ",
      DOB: "2018-04-29T00:00:00",
      Address1: "18928 greydale ",
      Address2: "",
      City: "Detroit ",
      State: "Mi",
      Zip: "48219",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "Yes",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "Daijanair Johnson ",
      grade: "K",
      DPSCD: "Yes",
      FirstChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      SecondChoiceSchool: "Bates Academy",
      ThirdChoiceSchool: "Chrysler Elementary",
      StudentNumber: 48062,
      StudentNumberRe: 48062,
      DPSCDSchool: "Foreign Language Immersion and Cultural Studies",
      OtherLanguage: "No",
      LanguageFirstChoice: "French",
      LanguageSecondChoice: "Spanish",
      LanguageThirdChoice: "Japanese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "Yes, I have one or more additional students entering grades 2-6",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "FLICS",
      SiblingAttendingNames: "Anyah Norwood ",
      SiblingsApplyingNames: "Rakai Hawkins ",
      SEMCOG: "NaN",
      OODSchool: "NaN",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "36241984",
      completedAt: "2023-06-22T21:11:46.0732530Z",
      FullName: "Leiah lanton ",
      EnteringPreK: "No",
      ParentFirstName: "Jazmen ",
      ParentLastName: "Evans ",
      ParentPhone: "+13139481228",
      ParentEmail: "Jazmen55@gmail.com",
      FirstName: "Leiah ",
      LastName: "Lanton ",
      DOB: "2016-10-18T00:00:00",
      Address1: "19146 Curtis st",
      Address2: "",
      City: "Detroit ",
      State: "Michigan ",
      Zip: "48219",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "Jazmen Evans ",
      grade: "2",
      DPSCD: "Yes",
      FirstChoiceSchool: "Edison Elementary",
      SecondChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      ThirdChoiceSchool: "None",
      StudentNumber: 0,
      StudentNumberRe: 0,
      DPSCDSchool: "Charles Wright Academy of Arts and Science",
      OtherLanguage: "No",
      LanguageFirstChoice: "Spanish",
      LanguageSecondChoice: "Chinese",
      LanguageThirdChoice: "French",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "Yes",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "Leiah lanton and rhylee Gilmore ",
      SEMCOG: "NaN",
      OODSchool: "NaN",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "40204542",
      completedAt: "2023-06-05T03:43:18.9576070Z",
      FullName: "Jacob Roland Whittaker ",
      EnteringPreK: "No",
      ParentFirstName: "Ken ",
      ParentLastName: "Whittaker",
      ParentPhone: "+13135026946",
      ParentEmail: "krwjr313@gmail.com",
      FirstName: "Jacob",
      LastName: "Whittaker",
      DOB: "2018-06-12T00:00:00",
      Address1: "18495 Griggs St",
      Address2: "",
      City: "Detroit",
      State: "Michigan",
      Zip: "48221",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Ken Whittaker Jr",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "The School at Marygrove",
      ThirdChoiceSchool: "Chrysler Elementary",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "John Evans Montessori Academy ",
      OtherSchoolLocation: "Detroit, Michigan"
    },
    {
      submissionId: "40204343",
      completedAt: "2023-06-05T03:04:04.2954190Z",
      FullName: "Avah La'Nae Hardin ",
      EnteringPreK: "No",
      ParentFirstName: "Diamond",
      ParentLastName: "Hardin",
      ParentPhone: "+13137402781",
      ParentEmail: "Diamondhardin2017@gmail.com",
      FirstName: "Avah ",
      LastName: "Hardin",
      DOB: "2018-08-21T00:00:00",
      Address1: "18095 Woodingham dr ",
      Address2: "",
      City: "Detroit ",
      State: "Mi ",
      Zip: "48221",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Diamond Hardin",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "The School at Marygrove",
      SecondChoiceSchool: "None",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "Vandeburg Elementary School ",
      OtherSchoolLocation: "Redford "
    },
    {
      submissionId: "40202420",
      completedAt: "2023-06-04T21:14:08.8509310Z",
      FullName: "Grayson Marc Anthony Newton",
      EnteringPreK: "No",
      ParentFirstName: "Tahmyya",
      ParentLastName: "Johnson",
      ParentPhone: "+13135980340",
      ParentEmail: "tahmyya.johnson@gmail.com",
      FirstName: "Grayson",
      LastName: "Newton",
      DOB: "2018-10-01T00:00:00",
      Address1: "4336 Lakewood St",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48215",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "Yes",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Tahmyya Johnson",
      grade: "K",
      DPSCD: "Yes",
      FirstChoiceSchool: "Chrysler Elementary",
      SecondChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      ThirdChoiceSchool: "Bates Academy",
      StudentNumber: 0,
      StudentNumberRe: 0,
      DPSCDSchool: "Paul Robeson Malcolm X Academy",
      OtherLanguage: "No",
      LanguageFirstChoice: "Chinese",
      LanguageSecondChoice: "Japanese",
      LanguageThirdChoice: "Spanish",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "Chrysler",
      SiblingAttendingNames: "Chassity Newton",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "NaN",
      OODSchool: "NaN",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "40195709",
      completedAt: "2023-06-03T15:33:15.3798510Z",
      FullName: "Colton Bennett Lamb",
      EnteringPreK: "No",
      ParentFirstName: "Shirlene ",
      ParentLastName: "Cherry",
      ParentPhone: "+13135581072",
      ParentEmail: "stcherry85@gmail.com",
      FirstName: "Colton ",
      LastName: "Lamb",
      DOB: "2018-05-29T00:00:00",
      Address1: "16729 Glastonbury ",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48219",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "Shirlene Cherry",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "The School at Marygrove",
      SecondChoiceSchool: "None",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "Braylen Cherry",
      SEMCOG: "No",
      OODSchool: "Little Scholars ",
      OtherSchoolLocation: "Detroit MI"
    },
    {
      submissionId: "40076276",
      completedAt: "2023-06-02T17:45:44.6278090Z",
      FullName: "Rosemary Jerry",
      EnteringPreK: "No",
      ParentFirstName: "Lula",
      ParentLastName: "Taylor",
      ParentPhone: "+13132584401",
      ParentEmail: "lula.e.taylor@gmail.com",
      FirstName: "Rosemary",
      LastName: "Jerry",
      DOB: "2018-10-17T00:00:00",
      Address1: "9327 Ashton Ave",
      Address2: "",
      City: "Detroit",
      State: "Michigan",
      Zip: "48228",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Lula Taylor",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Edison Elementary",
      SecondChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "French",
      LanguageSecondChoice: "Spanish",
      LanguageThirdChoice: "Chinese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Old Redford Academy - Middle School (22122 W Mcnichols Rd, Detroit)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "40058714",
      completedAt: "2023-06-02T17:34:31.9657170Z",
      FullName: "Julian Maradiaga Cadenas",
      EnteringPreK: "No",
      ParentFirstName: "Clelyn ",
      ParentLastName: "Cadenas ",
      ParentPhone: "+15619095089",
      ParentEmail: "cadenasmargoht2013@yahoo.com",
      FirstName: "Julian",
      LastName: "Maradiaga ",
      DOB: "2018-06-15T00:00:00",
      Address1: "17513 trinity St ",
      Address2: "",
      City: "Detroit ",
      State: "Michigan ",
      Zip: "48219",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "Yes",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Clelyn Cadenas ",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      SecondChoiceSchool: "Academy of the Americas",
      ThirdChoiceSchool: "Edison Elementary",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "Yes",
      LanguageFirstChoice: "Spanish",
      LanguageSecondChoice: "French",
      LanguageThirdChoice: "Japanese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "Yes",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "FLICS; Academy of the Americas; Edison",
      SiblingAttendingNames: "Helen Dormes Cadenas",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "Focus hope ",
      OtherSchoolLocation: "Detroit MI"
    },
    {
      submissionId: "40050691",
      completedAt: "2023-06-02T16:34:38.8437670Z",
      FullName: "Julián Maradiaga Cadenas ",
      EnteringPreK: "Yes",
      ParentFirstName: "Clelyn ",
      ParentLastName: "Cadenas",
      ParentPhone: "+15619095089",
      ParentEmail: "cadenasmargoht2013@yahoo.com",
      FirstName: "Julian",
      LastName: "Maradiaga Cadenas",
      DOB: "2018-06-15T00:00:00",
      Address1: "17513 trinity St ",
      Address2: "",
      City: "Detroit ",
      State: "MI",
      Zip: "48219",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "Yes",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "Academy of the Americas",
      SiblingAttendingNames: "Helen Maricruz ",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "Focus hope ",
      OtherSchoolLocation: "Detroi Míchigan "
    },
    {
      submissionId: "40042251",
      completedAt: "2023-06-02T16:13:28.4179690Z",
      FullName: "A'miyah Jones",
      EnteringPreK: "Yes",
      ParentFirstName: "Theresa",
      ParentLastName: "Jeffries",
      ParentPhone: "+13132091149",
      ParentEmail: "loveetheresa@icloud.com",
      FirstName: "A'miyah",
      LastName: "Jones",
      DOB: "2018-08-26T00:00:00",
      Address1: "9919 Mark Twain",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48227",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "Starfish ",
      OtherSchoolLocation: "Livonia MI"
    },
    {
      submissionId: "40039476",
      completedAt: "2023-06-02T16:06:32.4235370Z",
      FullName: "Ryleigh Watson",
      EnteringPreK: "Yes",
      ParentFirstName: "Amber",
      ParentLastName: "Peterson",
      ParentPhone: "+12484456235",
      ParentEmail: "Kdnjacmp@gmail.com",
      FirstName: "Ryleigh",
      LastName: "Watson",
      DOB: "2018-12-20T00:00:00",
      Address1: "2439 Concord",
      Address2: "",
      City: "Detroit",
      State: "Michigan ",
      Zip: "48207",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "N/a",
      OtherSchoolLocation: "N/a"
    },
    {
      submissionId: "40000117",
      completedAt: "2023-06-02T14:28:06.5523730Z",
      FullName: "Kairo Schultz",
      EnteringPreK: "No",
      ParentFirstName: "Brandy",
      ParentLastName: "Holmes",
      ParentPhone: "+13137063954",
      ParentEmail: "brandy.t.holmes@gmail.com",
      FirstName: "Kairo",
      LastName: "Schultz",
      DOB: "2018-08-10T00:00:00",
      Address1: "14393 Timberline Dr",
      Address2: "",
      City: "Taylor",
      State: "MI",
      Zip: "48180",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Brandy Holmes",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      SecondChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      ThirdChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "Japanese",
      LanguageSecondChoice: "French",
      LanguageThirdChoice: "Spanish",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Homeschool",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39997807",
      completedAt: "2023-06-02T12:46:08.8269480Z",
      FullName: "Ta'Jah Omar ",
      EnteringPreK: "No",
      ParentFirstName: "Nichelle",
      ParentLastName: "Omar",
      ParentPhone: "+12489156540",
      ParentEmail: "msnichelleomar@hotmail.com",
      FirstName: "Ta'Jah ",
      LastName: "Omar",
      DOB: "2016-05-04T00:00:00",
      Address1: "19216 Winthrop St",
      Address2: "",
      City: "Detroit ",
      State: "MI",
      Zip: "48235",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Nichelle Omar ",
      grade: "2",
      DPSCD: "Yes",
      FirstChoiceSchool: "Palmer Park Preparatory Academy",
      SecondChoiceSchool: "The School at Marygrove",
      ThirdChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      StudentNumber: 33917,
      StudentNumberRe: 33917,
      DPSCDSchool: "Paul Robeson Malcolm X Academy",
      OtherLanguage: "No",
      LanguageFirstChoice: "Spanish",
      LanguageSecondChoice: "Japanese",
      LanguageThirdChoice: "Chinese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "NaN",
      OODSchool: "NaN",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39996268",
      completedAt: "2023-06-02T04:26:13.9521910Z",
      FullName: "Eva Angel Dorothy King",
      EnteringPreK: "No",
      ParentFirstName: "Tiffany",
      ParentLastName: "King",
      ParentPhone: "+13137532391",
      ParentEmail: "tiffanyking0815@gmail.com",
      FirstName: "Eva ",
      LastName: "King",
      DOB: "2015-12-24T00:00:00",
      Address1: "19120 Parkside",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48221",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "Tiffany King",
      grade: "2",
      DPSCD: "No",
      FirstChoiceSchool: "Palmer Park Preparatory Academy",
      SecondChoiceSchool: "Edmonson Elementary",
      ThirdChoiceSchool: "Edison Elementary",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "Ava Mae Lucinda King (Twin sisters)",
      SEMCOG: "Yes",
      OODSchool: "Crescent Academy PK-1 (17570 West 12 Mile Road, Southfield)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39996212",
      completedAt: "2023-06-02T04:15:36.8643910Z",
      FullName: "Ava Mae Lucinda King",
      EnteringPreK: "No",
      ParentFirstName: "Tiffany",
      ParentLastName: "King",
      ParentPhone: "+13137532391",
      ParentEmail: "tiffanyking0815@gmail.com",
      FirstName: "Ava ",
      LastName: "King",
      DOB: "2015-12-24T00:00:00",
      Address1: "19120 Parkside ",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48221",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "Tiffany King",
      grade: "2",
      DPSCD: "No",
      FirstChoiceSchool: "Palmer Park Preparatory Academy",
      SecondChoiceSchool: "Edmonson Elementary",
      ThirdChoiceSchool: "Edison Elementary",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "Eva Angel Dorothy King (Twin sisters)",
      SEMCOG: "Yes",
      OODSchool: "Crescent Academy PK-1 (17570 West 12 Mile Road, Southfield)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39901333",
      completedAt: "2023-06-01T17:17:01.0421120Z",
      FullName: "Royce A'mour Manning",
      EnteringPreK: "No",
      ParentFirstName: "Randell",
      ParentLastName: "Manning",
      ParentPhone: "+12489936666",
      ParentEmail: "RandellManning41@gmail.com",
      FirstName: "Royce",
      LastName: "Manning",
      DOB: "2018-02-01T00:00:00",
      Address1: "15490 Prest st ",
      Address2: "",
      City: "Detroit",
      State: "Mi",
      Zip: "48227",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Randell Manning",
      grade: "K",
      DPSCD: "Yes",
      FirstChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      SecondChoiceSchool: "Bates Academy",
      ThirdChoiceSchool: "None",
      StudentNumber: 0,
      StudentNumberRe: 0,
      DPSCDSchool: "Foreign Language Immersion and Cultural Studies",
      OtherLanguage: "No",
      LanguageFirstChoice: "Spanish",
      LanguageSecondChoice: "French",
      LanguageThirdChoice: "Chinese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "NaN",
      OODSchool: "NaN",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39879916",
      completedAt: "2023-06-01T14:43:38.6083050Z",
      FullName: "Isiah Akinruli",
      EnteringPreK: "No",
      ParentFirstName: "Mary",
      ParentLastName: "Sayle-Akinruli",
      ParentPhone: "+13133501024",
      ParentEmail: "msmsayle@yahoo.com",
      FirstName: "Isiah",
      LastName: "Akinruli",
      DOB: "2017-09-06T00:00:00",
      Address1: "19180 Pierson",
      Address2: "",
      City: "Detroit",
      State: "Michigan",
      Zip: "48219",
      Country: "US",
      Gender: "Male",
      ESE: "Yes",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Mary Sayle-Akinruli",
      grade: "K",
      DPSCD: "Yes",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "The School at Marygrove",
      ThirdChoiceSchool: "Edmonson Elementary",
      StudentNumber: 2659343249,
      StudentNumberRe: 2659343249,
      DPSCDSchool: "Emerson Elementary-Middle School",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "NaN",
      OODSchool: "NaN",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39862305",
      completedAt: "2023-06-01T13:46:57.6242480Z",
      FullName: "Santina Eerick Harris",
      EnteringPreK: "Yes",
      ParentFirstName: "India ",
      ParentLastName: "Hardrick ",
      ParentPhone: "+13133911974",
      ParentEmail: "hardrick.indi@gmail.com",
      FirstName: "Santina",
      LastName: "Harris ",
      DOB: "2019-05-08T00:00:00",
      Address1: "1989 Pasadena st",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48238",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "None",
      OtherSchoolLocation: "None"
    },
    {
      submissionId: "39848790",
      completedAt: "2023-06-01T13:03:01.9193100Z",
      FullName: "Charleigh-Rose Burns",
      EnteringPreK: "No",
      ParentFirstName: "Charmaine ",
      ParentLastName: "Payton ",
      ParentPhone: "+15863036063",
      ParentEmail: "cpayton91@gmail.com",
      FirstName: "Charleigh-Rose",
      LastName: "Burns",
      DOB: "2018-08-17T00:00:00",
      Address1: "28638 Bridge St.",
      Address2: "",
      City: "Garden City",
      State: "MI",
      Zip: "48135",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Charmaine Payton ",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      ThirdChoiceSchool: "The School at Marygrove",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "Chinese",
      LanguageSecondChoice: "Spanish",
      LanguageThirdChoice: "Japanese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "Lathers elementary ",
      OtherSchoolLocation: "Garden City MI"
    },
    {
      submissionId: "39545300",
      completedAt: "2023-05-31T23:16:35.0142330Z",
      FullName: "Skyy amore Justice",
      EnteringPreK: "No",
      ParentFirstName: "Starrcandes",
      ParentLastName: "Justice",
      ParentPhone: "+13133923929",
      ParentEmail: "starrcandesjustice@gmail.com",
      FirstName: "skyy",
      LastName: "Justice",
      DOB: "2018-09-14T00:00:00",
      Address1: "16144 Snowden",
      Address2: "",
      City: "Detroit",
      State: "mi",
      Zip: "48235",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "starrcandes justice",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "The School at Marygrove",
      SecondChoiceSchool: "Bates Academy",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "No",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Mary grove starfish",
      OtherSchoolLocation: "detroit"
    },
    {
      submissionId: "39535320",
      completedAt: "2023-05-31T22:53:10.5049880Z",
      FullName: "Skyy Amore Justice ",
      EnteringPreK: "Yes",
      ParentFirstName: "Starrcandes ",
      ParentLastName: "Justice",
      ParentPhone: "+13133923929",
      ParentEmail: "Starrcandesjustice@gmail.com",
      FirstName: "Skyy",
      LastName: "Justice",
      DOB: "2018-09-14T00:00:00",
      Address1: "16144 Snowden ",
      Address2: "",
      City: "Detroit",
      State: "Michigan",
      Zip: "48235",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Mary grove starfish",
      OtherSchoolLocation: "Detroit MI"
    },
    {
      submissionId: "39454972",
      completedAt: "2023-05-31T19:47:48.0363540Z",
      FullName: "Lyric Milan Jones",
      EnteringPreK: "No",
      ParentFirstName: "Destiny",
      ParentLastName: "Phillips",
      ParentPhone: "+13136100443",
      ParentEmail: "Destinyphillips031295@yahoo.com",
      FirstName: "Lyric ",
      LastName: "Jones",
      DOB: "2016-08-15T00:00:00",
      Address1: "29798 Gregg Drive",
      Address2: "",
      City: "Roseville",
      State: "MI",
      Zip: "48066",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "Destiny Phillips ",
      grade: "2",
      DPSCD: "No",
      FirstChoiceSchool: "The School at Marygrove",
      SecondChoiceSchool: "Edison Elementary",
      ThirdChoiceSchool: "Edmonson Elementary",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have not registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "Dreaym Amor Jones ",
      SEMCOG: "Yes",
      OODSchool: "Westfield Charter Academy (27201 W Chicago, Redford)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39403162",
      completedAt: "2023-05-31T17:47:22.8507140Z",
      FullName: "SIRE SILAS BUFFINGTON",
      EnteringPreK: "No",
      ParentFirstName: "CARLITA",
      ParentLastName: "BUFFINGTON",
      ParentPhone: "+13139784777",
      ParentEmail: "carlitajb2@gmail.com",
      FirstName: "Sire",
      LastName: "Buffington",
      DOB: "2017-05-27T00:00:00",
      Address1: "1204 EDISON",
      Address2: "",
      City: "Detroit",
      State: "MICHIGAN",
      Zip: "48202",
      Country: "US",
      Gender: "Male",
      ESE: "Yes",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "CARLITA BUFFINGTON",
      grade: "1",
      DPSCD: "No",
      FirstChoiceSchool: "Palmer Park Preparatory Academy",
      SecondChoiceSchool: "None",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "UPREP",
      OtherSchoolLocation: "DETROIT, MICHIGAN"
    },
    {
      submissionId: "39356866",
      completedAt: "2023-05-31T15:59:48.6279600Z",
      FullName: "Zara Victoria Kimpson",
      EnteringPreK: "Yes",
      ParentFirstName: "Justin",
      ParentLastName: "Kimpson",
      ParentPhone: "+13133502803",
      ParentEmail: "justin.kimpson@gmail.com",
      FirstName: "Zara",
      LastName: "Kimpson",
      DOB: "2018-12-21T00:00:00",
      Address1: "740 Lemay",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48214",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Grosse Pointe Academy (171 Lake Shore Rd, Grosse Pointe Farms)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39328836",
      completedAt: "2023-05-31T14:55:01.9039390Z",
      FullName: "Angela Pinchem",
      EnteringPreK: "No",
      ParentFirstName: "Angela",
      ParentLastName: "Pinchem",
      ParentPhone: "+13133542046",
      ParentEmail: "angela1pinch@gmail.com",
      FirstName: "Ava",
      LastName: "Pinchem",
      DOB: "2017-09-06T00:00:00",
      Address1: "2606 Woodward Ave",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48201",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Angela pinchem",
      grade: "1",
      DPSCD: "No",
      FirstChoiceSchool: "Edmonson Elementary",
      SecondChoiceSchool: "The School at Marygrove",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "For Kids Sake Montessori ",
      OtherSchoolLocation: "Southfield, MI"
    },
    {
      submissionId: "39317949",
      completedAt: "2023-05-31T13:33:24.1966420Z",
      FullName: "Zariah Mireya Spivey ",
      EnteringPreK: "Yes",
      ParentFirstName: "Jermaine",
      ParentLastName: "Spivey ",
      ParentPhone: "+12482529408",
      ParentEmail: "alvon8686@gmail.com",
      FirstName: "Zariah",
      LastName: "Spivey",
      DOB: "2015-03-11T00:00:00",
      Address1: "14413 Mark Twain ",
      Address2: "",
      City: "Detroit ",
      State: "Mi",
      Zip: "48227",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Adams-Young Building (13130 Grove St, Detroit)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39317030",
      completedAt: "2023-05-31T11:56:42.9516200Z",
      FullName: "Nadia Zoey Brown",
      EnteringPreK: "No",
      ParentFirstName: "Richard/Sharon",
      ParentLastName: "Brown",
      ParentPhone: "+17349159371",
      ParentEmail: "senr1982@gmail.com",
      FirstName: "Nadia",
      LastName: "Brown",
      DOB: "2017-12-21T00:00:00",
      Address1: "12624 Monica St.",
      Address2: "",
      City: "Detroit",
      State: "Michigan",
      Zip: "48238",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Sharon Brown",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "Spanish",
      LanguageSecondChoice: "Spanish",
      LanguageThirdChoice: "Spanish",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "Proverbs 22:6 Christian Academy",
      OtherSchoolLocation: "Detroit, Michigan"
    },
    {
      submissionId: "39296188",
      completedAt: "2023-05-30T22:07:16.0177320Z",
      FullName: "Rylee Elyse Bonner",
      EnteringPreK: "No",
      ParentFirstName: "Michele",
      ParentLastName: "Herron",
      ParentPhone: "+13135747821",
      ParentEmail: "herron.michele@gmail.com",
      FirstName: "Rylee",
      LastName: "Bonner",
      DOB: "2016-01-18T00:00:00",
      Address1: "20783 Mitchelldale Ave",
      Address2: "",
      City: "Ferndale",
      State: "MI",
      Zip: "48220",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Michele Herron",
      grade: "2",
      DPSCD: "No",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "Spanish",
      LanguageSecondChoice: "French",
      LanguageThirdChoice: "Chinese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Key Elementary School (23400 Jerome St, Oak Park)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39206780",
      completedAt: "2023-05-30T18:42:52.2292540Z",
      FullName: "Melanie Juliana calel quinonez",
      EnteringPreK: "Yes",
      ParentFirstName: "Julio ",
      ParentLastName: "Calel Gomez ",
      ParentPhone: "+13137483371",
      ParentEmail: "Julio33990@gmail.com",
      FirstName: "Melanie ",
      LastName: "Calel quinonez",
      DOB: "2018-02-21T00:00:00",
      Address1: "3842 31 st",
      Address2: "",
      City: "Detroit ",
      State: "Mi",
      Zip: "48210",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "Yes",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "Academy of the Americas",
      SiblingAttendingNames: "Donovan Tarrant ",
      SiblingsApplyingNames: "Donovan Tarrant ",
      SEMCOG: "No",
      OODSchool: "Matrix",
      OtherSchoolLocation: "Detroit "
    },
    {
      submissionId: "36262438",
      completedAt: "2023-05-30T18:31:40.7528980Z",
      FullName: "Margot Gallimore",
      EnteringPreK: "No",
      ParentFirstName: "Sarah",
      ParentLastName: "Gallimore",
      ParentPhone: "+15133078935",
      ParentEmail: "sarahannegallimore@gmail.com",
      FirstName: "Margot",
      LastName: "Gallimore",
      DOB: "2018-05-09T00:00:00",
      Address1: "463 Lakewood",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48215",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Sarah Gallimore ",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Palmer Park Preparatory Academy",
      SecondChoiceSchool: "The School at Marygrove",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "No",
      OODSchool: "Waldorf - PreK",
      OtherSchoolLocation: "Detroit, MI"
    },
    {
      submissionId: "39180861",
      completedAt: "2023-05-30T17:45:04.6851950Z",
      FullName: "DeShawn Hugle",
      EnteringPreK: "No",
      ParentFirstName: "Patsy",
      ParentLastName: "Blount",
      ParentPhone: "+13134430035",
      ParentEmail: "Blountpatsy@yahoo.com",
      FirstName: "DeShawn",
      LastName: "Hugle",
      DOB: "2016-12-09T00:00:00",
      Address1: "18717 Lauder St",
      Address2: "",
      City: "Detroit ",
      State: "Mi",
      Zip: "48235",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Patsy Blount",
      grade: "1",
      DPSCD: "No",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "Academy of the Americas",
      ThirdChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "French",
      LanguageSecondChoice: "Spanish",
      LanguageThirdChoice: "Chinese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Pippen palace",
      OtherSchoolLocation: "Detroit Mi"
    },
    {
      submissionId: "39108634",
      completedAt: "2023-05-30T15:03:41.5225450Z",
      FullName: "John Lawrence ",
      EnteringPreK: "No",
      ParentFirstName: "Regina",
      ParentLastName: "Howard",
      ParentPhone: "+13132903453",
      ParentEmail: "gina5393@gmail.com",
      FirstName: "John",
      LastName: "Lawrence ",
      DOB: "2018-01-10T00:00:00",
      Address1: "15881 Meyers Rd",
      Address2: "",
      City: "Detroit ",
      State: "Michigan",
      Zip: "48227",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "Yes",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Regina Howard ",
      grade: "K",
      DPSCD: "Yes",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "Bates Academy",
      ThirdChoiceSchool: "Academy of the Americas",
      StudentNumber: 49031,
      StudentNumberRe: 49031,
      DPSCDSchool: "Bates Academy",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "Bates",
      SiblingAttendingNames: "Autumn Howard ",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "NaN",
      OODSchool: "NaN",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39088402",
      completedAt: "2023-05-30T12:29:57.9589900Z",
      FullName: "Donovan Lee Pickett",
      EnteringPreK: "No",
      ParentFirstName: "Jessica",
      ParentLastName: "Pickett",
      ParentPhone: "+13138080289",
      ParentEmail: "jessicachristine1219@comcast.net",
      FirstName: "Donovan",
      LastName: "Pickett",
      DOB: "2026-02-24T00:00:00",
      Address1: "17290 Shaftsbury Ave",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48212",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "Yes",
      DPSCDStaff: "Yes",
      ParentSignature: "Jessica Pickett",
      grade: "2",
      DPSCD: "No",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "French",
      LanguageSecondChoice: "Spanish",
      LanguageThirdChoice: "Japanese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "Dorian Pickett (already accepted)",
      SEMCOG: "Yes",
      OODSchool: "Pepper Elementary School (24301 Church St, Oak Park)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39082971",
      completedAt: "2023-05-29T18:45:30.6336280Z",
      FullName: "John Howard",
      EnteringPreK: "No",
      ParentFirstName: "John ",
      ParentLastName: "Howard",
      ParentPhone: "+13134710102",
      ParentEmail: "Jlhoward45@gmail.com",
      FirstName: "John",
      LastName: "Howard",
      DOB: "2016-11-13T00:00:00",
      Address1: "12707 Birwood",
      Address2: "",
      City: "Detroit ",
      State: "MI",
      Zip: "48239",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "John Howard",
      grade: "2",
      DPSCD: "No",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "The School at Marygrove",
      ThirdChoiceSchool: "Palmer Park Preparatory Academy",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Jane Addams Elementary School (14025 Berwyn, Redford)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39074223",
      completedAt: "2023-05-28T12:37:07.4973510Z",
      FullName: "Westley Lawerence Winfield Parks",
      EnteringPreK: "No",
      ParentFirstName: "Martha",
      ParentLastName: "Winfield ",
      ParentPhone: "+13136754119",
      ParentEmail: "Parks.martha13@gmail.com",
      FirstName: "Westley ",
      LastName: "Winfield-Parks",
      DOB: "2017-01-19T00:00:00",
      Address1: "19195 Lancashire ",
      Address2: "",
      City: "Detroit ",
      State: "Mi",
      Zip: "48223",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "Martha Winfield ",
      grade: "1",
      DPSCD: "No",
      FirstChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      SecondChoiceSchool: "Bates Academy",
      ThirdChoiceSchool: "The School at Marygrove",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "Spanish",
      LanguageSecondChoice: "French",
      LanguageThirdChoice: "Chinese",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "Yes, I have one or more additional students entering grades 2-6",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "Carter Washington-Parks",
      SEMCOG: "Yes",
      OODSchool: "Key Elementary School (23400 Jerome St, Oak Park)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39073052",
      completedAt: "2023-05-28T03:02:18.9576840Z",
      FullName: "Nas Karrell Burns",
      EnteringPreK: "No",
      ParentFirstName: "Elicia ",
      ParentLastName: "Jones",
      ParentPhone: "+13137064591",
      ParentEmail: "eliciajones.goals@gmail.com",
      FirstName: "Nas",
      LastName: "Burns",
      DOB: "2015-11-04T00:00:00",
      Address1: "16536 Inverness St",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48221",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Elicia Jones",
      grade: "2",
      DPSCD: "No",
      FirstChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      SecondChoiceSchool: "The School at Marygrove",
      ThirdChoiceSchool: "Bates Academy",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "Japanese",
      LanguageSecondChoice: "Spanish",
      LanguageThirdChoice: "French",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "University Preparatory Science and Math - Elementary (2251 Antietam Ave, Detroit)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39069581",
      completedAt: "2023-05-27T13:58:49.6519990Z",
      FullName: "Rebekah Palmore ",
      EnteringPreK: "No",
      ParentFirstName: "Elexa",
      ParentLastName: "Riggins ",
      ParentPhone: "+13138544555",
      ParentEmail: "Edriggins30@gmail.com",
      FirstName: "Rebekah",
      LastName: "Palmore",
      DOB: "2017-06-06T00:00:00",
      Address1: "15095 Littlefield ",
      Address2: "",
      City: "Detroit",
      State: "Michigan",
      Zip: "48227",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Elexa Riggins ",
      grade: "1",
      DPSCD: "Yes",
      FirstChoiceSchool: "The School at Marygrove",
      SecondChoiceSchool: "Palmer Park Preparatory Academy",
      ThirdChoiceSchool: "The School at Marygrove",
      StudentNumber: 33943,
      StudentNumberRe: 33943,
      DPSCDSchool: "Noble Elementary-Middle School",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "NaN",
      OODSchool: "NaN",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "39067839",
      completedAt: "2023-05-27T02:05:30.4799400Z",
      FullName: "King Bailey ",
      EnteringPreK: "No",
      ParentFirstName: "Jamesha ",
      ParentLastName: "Coats",
      ParentPhone: "+14423407244",
      ParentEmail: "Jameshacoats@gmail.com",
      FirstName: "King ",
      LastName: "Bailey",
      DOB: "2014-11-14T00:00:00",
      Address1: "3466 eastern pl",
      Address2: "",
      City: "Detroit",
      State: "Mi",
      Zip: "48208",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "Jamesha coats",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Edison Elementary",
      SecondChoiceSchool: "None",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "Serinity Hicks & trinity coats",
      SEMCOG: "No",
      OODSchool: "No school ",
      OtherSchoolLocation: "We just moved from Philadelphia "
    },
    {
      submissionId: "39062313",
      completedAt: "2023-05-26T14:46:23.7893340Z",
      FullName: "Erik Owens",
      EnteringPreK: "Yes",
      ParentFirstName: "Rayven",
      ParentLastName: "Walker",
      ParentPhone: "+13135020995",
      ParentEmail: "RayvenWalker25@gmail.com",
      FirstName: "Erik",
      LastName: "Owens",
      DOB: "2018-10-01T00:00:00",
      Address1: "16260 Northlawn ",
      Address2: "",
      City: "Detroit ",
      State: "MI",
      Zip: "48221",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Webster ",
      OtherSchoolLocation: "Hazel park"
    },
    {
      submissionId: "39061889",
      completedAt: "2023-05-26T13:54:58.1840050Z",
      FullName: "Zane  Redmond",
      EnteringPreK: "No",
      ParentFirstName: "LaTonya ",
      ParentLastName: "White ",
      ParentPhone: "+13139329376",
      ParentEmail: "latonyawhite1730@gmail.com",
      FirstName: "Zane ",
      LastName: "Redmond",
      DOB: "2017-10-15T00:00:00",
      Address1: "10003 Berkshire ",
      Address2: "",
      City: "Detroit ",
      State: "MI",
      Zip: "48224",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "LaTonya White ",
      grade: "1",
      DPSCD: "No",
      FirstChoiceSchool: "Edmonson Elementary",
      SecondChoiceSchool: "None",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Pembroke Academy (19940 Mansfield St, Detroit)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "38865599",
      completedAt: "2023-05-25T20:22:41.7237800Z",
      FullName: "Rylee Williamson ",
      EnteringPreK: "No",
      ParentFirstName: "SeAndra",
      ParentLastName: "McGee",
      ParentPhone: "+12482590907",
      ParentEmail: "seandra2203@gmail.com",
      FirstName: "Rylee ",
      LastName: "Williamson ",
      DOB: "2016-07-06T00:00:00",
      Address1: "187 Hill",
      Address2: "",
      City: "Highland Park ",
      State: "Michigan ",
      Zip: "48203",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "SeAndra McGee ",
      grade: "2",
      DPSCD: "No",
      FirstChoiceSchool: "The School at Marygrove",
      SecondChoiceSchool: "None",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Grand River Academy (28111 8 Mile Rd, Livonia)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "38854084",
      completedAt: "2023-05-25T19:55:01.7345390Z",
      FullName: "Brave Magnolia Simpson",
      EnteringPreK: "Yes",
      ParentFirstName: "India",
      ParentLastName: "Foster",
      ParentPhone: "+12162121310",
      ParentEmail: "ifoster1819@gmail.com",
      FirstName: "Brave",
      LastName: "Simpson",
      DOB: "2019-04-07T00:00:00",
      Address1: "16900 Parkside St",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48221",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "Yes",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "Bates",
      SiblingAttendingNames: "Glory Simpson",
      SiblingsApplyingNames: "Brave Simpson, Glory Simpson",
      SEMCOG: "No",
      OODSchool: "Null",
      OtherSchoolLocation: "Null "
    },
    {
      submissionId: "38746890",
      completedAt: "2023-05-25T15:39:14.6805750Z",
      FullName: "Peyton Miyona White",
      EnteringPreK: "No",
      ParentFirstName: "Paige",
      ParentLastName: "Jenkins",
      ParentPhone: "+13136950738",
      ParentEmail: "Paigejenkins21@gmail.com",
      FirstName: "Peyton",
      LastName: "White",
      DOB: "2017-12-29T00:00:00",
      Address1: "10529 curtis",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48221",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Paige jenkins ",
      grade: "1",
      DPSCD: "Yes",
      FirstChoiceSchool: "The School at Marygrove",
      SecondChoiceSchool: "None",
      ThirdChoiceSchool: "None",
      StudentNumber: 43896,
      StudentNumberRe: 43896,
      DPSCDSchool: "Schulze Academy for Technology and Arts",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "NaN",
      OODSchool: "NaN",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "38733906",
      completedAt: "2023-05-25T15:08:14.7090340Z",
      FullName: "Erik Owens",
      EnteringPreK: "Yes",
      ParentFirstName: "Rayven",
      ParentLastName: "Walker",
      ParentPhone: "+13135020995",
      ParentEmail: "RayvenWalker25@gmail.com",
      FirstName: "Erik",
      LastName: "Owen",
      DOB: "2018-10-01T00:00:00",
      Address1: "16260 Northlawn ",
      Address2: "",
      City: "Detroit ",
      State: "MI",
      Zip: "48221",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Webster headstart",
      OtherSchoolLocation: "Hazel park mi "
    },
    {
      submissionId: "35731814",
      completedAt: "2023-05-25T14:59:35.9912380Z",
      FullName: "Jaden Jordan",
      EnteringPreK: "No",
      ParentFirstName: "Raven ",
      ParentLastName: "Jordan",
      ParentPhone: "+13136801011",
      ParentEmail: "ejmath@gmail.com",
      FirstName: "Jaden",
      LastName: "Jordan",
      DOB: "2016-09-29T00:00:00",
      Address1: "16844 Griggs",
      Address2: "",
      City: "Detroit",
      State: "Michigan",
      Zip: "48221",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Raven Jordan",
      grade: "2",
      DPSCD: "No",
      FirstChoiceSchool: "The School at Marygrove",
      SecondChoiceSchool: "None",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Adams-Young Building (13130 Grove St, Detroit)",
      OtherSchoolLocation: "NaN"
    },
    {
      submissionId: "38723827",
      completedAt: "2023-05-24T19:37:51.8069430Z",
      FullName: "Katia Valeria Juan Chanas ",
      EnteringPreK: "Yes",
      ParentFirstName: "Catalina",
      ParentLastName: "Chanas Gomez",
      ParentPhone: "+13137405910",
      ParentEmail: "catalinagomezc1@gmail.com",
      FirstName: "Katia Valeria",
      LastName: "Juan Chanas",
      DOB: "2017-12-30T00:00:00",
      Address1: "2158 Scotten St ",
      Address2: "",
      City: "Detroit ",
      State: "Mi ",
      Zip: "48209",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "Yes",
      SiblingsApplying: "Yes",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "Academy of the Americas",
      SiblingAttendingNames: "Mario Chanas",
      SiblingsApplyingNames: "Mario Chanas ",
      SEMCOG: "No",
      OODSchool: "No school ",
      OtherSchoolLocation: "No school"
    },
    {
      submissionId: "38723579",
      completedAt: "2023-05-24T19:16:28.2336560Z",
      FullName: "Ava Jasmine Pinchem",
      EnteringPreK: "No",
      ParentFirstName: "Andre ",
      ParentLastName: "Pinchem",
      ParentPhone: "+13134779547",
      ParentEmail: "dre_pinch@yahoo.com",
      FirstName: "Ava",
      LastName: "Pinchem",
      DOB: "2017-09-06T00:00:00",
      Address1: "2606 Woodward ",
      Address2: "",
      City: "Detroit",
      State: "Mi",
      Zip: "48201",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Andre Pinchem",
      grade: "1",
      DPSCD: "No",
      FirstChoiceSchool: "Edmonson Elementary",
      SecondChoiceSchool: "Palmer Park Preparatory Academy",
      ThirdChoiceSchool: "The School at Marygrove",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "For Kids Sake Montessori ",
      OtherSchoolLocation: "Southfield, MI"
    },
    {
      submissionId: "38722164",
      completedAt: "2023-05-24T16:46:19.7452870Z",
      FullName: "Jaiya LoReal Davis",
      EnteringPreK: "No",
      ParentFirstName: "Natasha",
      ParentLastName: "Rice",
      ParentPhone: "+13136430630",
      ParentEmail: "njrice0719@gmail.com",
      FirstName: "Jaiya ",
      LastName: "Davis",
      DOB: "2018-03-07T00:00:00",
      Address1: "17344 Ohio St",
      Address2: "",
      City: "Detroit",
      State: " MI",
      Zip: "48221",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Natasha Rice ",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Foreign Language Immersion and Cultural Studies School",
      SecondChoiceSchool: "Bates Academy",
      ThirdChoiceSchool: "The School at Marygrove",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "No",
      LanguageFirstChoice: "Spanish",
      LanguageSecondChoice: "Chinese",
      LanguageThirdChoice: "French",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "No",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "New St.Paul Head start",
      OtherSchoolLocation: "Detroit mi"
    },
    {
      submissionId: "38720876",
      completedAt: "2023-05-24T14:12:47.6645580Z",
      FullName: "Lenox Saddler ",
      EnteringPreK: "Yes",
      ParentFirstName: "Brittney ",
      ParentLastName: "Cooksey ",
      ParentPhone: "+13137785521",
      ParentEmail: "Brittneysaddler@yahoo.com",
      FirstName: "Lenox",
      LastName: "Saddler",
      DOB: "2018-01-05T00:00:00",
      Address1: "14435 Curtis",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48235",
      Country: "AC",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "NaN",
      grade: "Pre-K",
      DPSCD: "No",
      FirstChoiceSchool: "NaN",
      SecondChoiceSchool: "NaN",
      ThirdChoiceSchool: "NaN",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "NaN",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "NaN",
      ExamScheduleingConfirmation: "NaN",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "New St. Paul ",
      OtherSchoolLocation: "detroit has "
    },
    {
      submissionId: "37936796",
      completedAt: "2023-05-23T19:02:47.9077010Z",
      FullName: "Langston Ojo",
      EnteringPreK: "No",
      ParentFirstName: "Cukeyra",
      ParentLastName: "Blackshear",
      ParentPhone: "+13132585415",
      ParentEmail: "Cukeyra@yahoo.com",
      FirstName: "Langston",
      LastName: " Ojo",
      DOB: "2018-05-27T00:00:00",
      Address1: "1131 W Canfield ",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48201",
      Country: "US",
      Gender: "Male",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "No",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "Cukeyra Blackshear-Ojo ",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "Chrysler Elementary",
      ThirdChoiceSchool: "Academy of the Americas",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have not registered my child for the exam",
      SiblingAttendingSchools: "NaN",
      SiblingAttendingNames: "NaN",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Krissy's Development Center  ",
      OtherSchoolLocation: "Detroit, MI "
    },
    {
      submissionId: "38501355",
      completedAt: "2023-05-23T18:21:05.6443470Z",
      FullName: "Kensington Henderson",
      EnteringPreK: "No",
      ParentFirstName: "TaMia",
      ParentLastName: "Henderson",
      ParentPhone: "+13137289906",
      ParentEmail: "Mrs.011612@gmail.com",
      FirstName: "Kensington ",
      LastName: "Henderson",
      DOB: "2018-06-26T00:00:00",
      Address1: "20210  Monte Vista St",
      Address2: "",
      City: "Detroit",
      State: "MI",
      Zip: "48221",
      Country: "US",
      Gender: "Female",
      ESE: "No",
      Plan504: "No",
      SiblingAttending: "Yes",
      SiblingsApplying: "No",
      DPSCDStaff: "No",
      ParentSignature: "TaMia Henderson ",
      grade: "K",
      DPSCD: "No",
      FirstChoiceSchool: "Bates Academy",
      SecondChoiceSchool: "None",
      ThirdChoiceSchool: "None",
      StudentNumber: "NaN",
      StudentNumberRe: "NaN",
      DPSCDSchool: "NaN",
      OtherLanguage: "NaN",
      LanguageFirstChoice: "NaN",
      LanguageSecondChoice: "NaN",
      LanguageThirdChoice: "NaN",
      ExamSchedulingAgreement: "Yes",
      FLICSPreK: "NaN",
      AnotherStudentTesting: "No",
      ExamScheduleingConfirmation: "I have not registered my child for the exam",
      SiblingAttendingSchools: "Bates",
      SiblingAttendingNames: "Kaedence Henderson, Kassedy Henderson",
      SiblingsApplyingNames: "NaN",
      SEMCOG: "Yes",
      OODSchool: "Bates Academy (GSR program)",
      OtherSchoolLocation: "Detroit"
    }
  ]
}